# Common role handlers

---
- name: Restart SSH
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  listen: Restart SSH

- name: Restart Chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
  listen: Restart Chrony

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd
